### ISSUE TITLE
Adicionar labels ou indicações do que é o campo

### ISSUE THREAD

**Issue by angelicaameira** [angelicaameira/EasyDecision#36]
Não existem indicações sobre o que são os campos na tela

**Comment by antoniogermano** [comment]
O comentário no Pull Request estava errado e por isso essa issue não foi considerada concluída.
Para cada issue, é necessário colocar o "fixes", "closes" etc antes.

Foi colocado:
> fixes #43 #36

Deveria ter sido:

> fixes #43
> fixes #36
